export default defineNuxtConfig({
    css: [],
    compatibilityDate: '2025-07-15',
    devtools: { enabled: true },
    runtimeConfig: {
        public: {
            webVitalsEnabled: true,
            webVitalsDebug: false,
            webVitalsEndpoint: '/api/web-vitals',
        },
    },
    vite: {
        server: {
            allowedHosts: ['.ngrok-free.app', '.ngrok-free.dev'],
        },
        css: {
            devSourcemap: false,
            preprocessorOptions: {
                scss: {
                    api: 'modern-compiler',
                },
            },
        },
    },

    modules: ['@nuxtjs/i18n'],

    i18n: {
        defaultLocale: 'en',
        strategy: 'prefix_except_default',
        detectBrowserLanguage: false,

        locales: [
            {
                code: 'en',
                name: 'English',
                files: [
                    'en/layout/header/base.json',
                    'en/layout/header/accountLinks.json',
                    'en/layout/header/nav.json',
                    'en/layout/header/locale.json',
                    'en/layout/footer.json',
                    'en/home/seo.json',
                    'en/home/hero.json',
                    'en/home/productTypes.json',
                    'en/home/feature.json',
                    'en/home/reviews.json',
                    'en/home/guarantees.json',
                    'en/home/cta.json',
                    'en/layout/header/search.json',
                    'en/auth/login.json',
                    'en/auth/register.json',
                    'en/auth/profile.json',
                    'en/account/shell.json',
                    'en/account/addressBook.json',
                    'en/account/coupons.json',
                    'en/account/gallery.json',
                    'en/account/profile.json',
                    'en/account/orders.json',
                    'en/account/points.json',
                    'en/account/reviews.json',
                    'en/account/quoteRequests.json',
                    'en/product/guarantees.json',
                    'en/product/productDetails.json',
                    'en/product/products.json',
                    'en/product/story.json',
                    'en/product/reviews.json',
                    'en/cart/uploadArtwork.json',
                    'en/cart/cartPreview.json',
                ],
            },
            {
                code: 'kr',
                name: 'Korean',
                files: [
                    'kr/layout/header/base.json',
                    'kr/layout/header/accountLinks.json',
                    'kr/layout/header/nav.json',
                    'kr/layout/header/locale.json',
                    'kr/layout/footer.json',
                    'kr/home/seo.json',
                    'kr/home/hero.json',
                    'kr/home/productTypes.json',
                    'kr/home/feature.json',
                    'kr/home/reviews.json',
                    'kr/home/guarantees.json',
                    'kr/home/cta.json',
                    'kr/layout/header/search.json',
                    'kr/auth/login.json',
                    'kr/auth/register.json',
                    'kr/auth/profile.json',
                    'kr/account/shell.json',
                    'kr/account/addressBook.json',
                    'kr/account/coupons.json',
                    'kr/account/gallery.json',
                    'kr/account/profile.json',
                    'kr/account/orders.json',
                    'kr/account/points.json',
                    'kr/account/reviews.json',
                    'kr/account/quoteRequests.json',
                    'kr/product/guarantees.json',
                    'kr/product/productDetails.json',
                    'kr/product/products.json',
                    'kr/product/story.json',
                    'kr/product/reviews.json',
                    'kr/cart/uploadArtwork.json',
                    'kr/cart/cartPreview.json',
                ],
            },
        ],

        langDir: 'locales/',
    },
});
